package com.kwad.sdk.core.a.kwai;

import com.kwad.components.core.webview.a.kwai.h;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.a;
import com.kwad.components.core.webview.jshandler.aa;
import com.kwad.components.core.webview.jshandler.ab;
import com.kwad.components.core.webview.jshandler.ac;
import com.kwad.components.core.webview.jshandler.af;
import com.kwad.components.core.webview.jshandler.ai;
import com.kwad.components.core.webview.jshandler.aj;
import com.kwad.components.core.webview.jshandler.ak;
import com.kwad.components.core.webview.jshandler.am;
import com.kwad.components.core.webview.jshandler.b;
import com.kwad.components.core.webview.jshandler.f;
import com.kwad.components.core.webview.jshandler.n;
import com.kwad.components.core.webview.jshandler.o;
import com.kwad.components.core.webview.jshandler.q;
import com.kwad.components.core.webview.jshandler.r;
import com.kwad.components.core.webview.jshandler.u;
import com.kwad.components.core.webview.jshandler.v;
import com.kwad.components.core.webview.jshandler.w;
import com.kwad.components.core.webview.jshandler.z;
import com.kwad.components.core.webview.kwai.a;
import com.kwad.components.splash.SplashPreloadManager;
import com.kwad.components.splash.monitor.SplashMonitorInfo;
import com.kwad.sdk.f.a;
import com.kwad.sdk.f.b;

/* JADX INFO: loaded from: classes3.dex */
public final class bw {
    public static void wa() {
        el.wb().put(com.kwad.components.core.webview.a.a.t.class, new hn());
        el.wb().put(ab.a.class, new ap());
        el.wb().put(ai.a.class, new iq());
        el.wb().put(com.kwad.components.core.webview.a.a.n.class, new fu());
        el.wb().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new w());
        el.wb().put(h.b.class, new fy());
        el.wb().put(com.kwad.components.core.webview.a.a.d.class, new av());
        el.wb().put(com.kwad.components.core.webview.a.a.e.class, new be());
        el.wb().put(com.kwad.components.core.webview.a.a.p.class, new gy());
        el.wb().put(com.kwad.components.core.webview.a.a.x.class, new ip());
        el.wb().put(WebCardVideoPositionHandler.VideoPosition.class, new io());
        el.wb().put(com.kwad.components.core.webview.a.a.g.class, new bn());
        el.wb().put(b.a.class, new gu());
        el.wb().put(com.kwad.components.core.webview.a.a.h.class, new cc());
        el.wb().put(com.kwad.components.core.webview.kwai.c.class, new fl());
        el.wb().put(ac.a.class, new aw());
        el.wb().put(am.a.class, new ek());
        el.wb().put(f.a.class, new q());
        el.wb().put(q.a.class, new ij());
        el.wb().put(com.kwad.components.core.webview.a.a.a.class, new m());
        el.wb().put(com.kwad.components.core.webview.a.a.b.class, new ar());
        el.wb().put(ab.b.class, new aq());
        el.wb().put(com.kwad.components.core.i.a.class, new p());
        el.wb().put(SplashPreloadManager.PreLoadItem.class, new gd());
        el.wb().put(com.kwad.components.core.webview.a.a.f.class, new bk());
        el.wb().put(com.kwad.components.core.webview.a.a.i.class, new Cdo());
        el.wb().put(com.kwad.components.core.webview.a.a.o.class, new fw());
        el.wb().put(b.C0414b.class, new dn());
        el.wb().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new em());
        el.wb().put(com.kwad.components.core.webview.kwai.b.class, new fj());
        el.wb().put(r.a.class, new du());
        el.wb().put(com.kwad.components.core.webview.a.a.q.class, new ha());
        el.wb().put(aa.a.class, new an());
        el.wb().put(com.kwad.components.core.webview.a.a.w.class, new im());
        el.wb().put(aj.a.class, new hx());
        el.wb().put(com.kwad.components.core.webview.a.a.v.class, new ik());
        el.wb().put(v.b.class, new dq());
        el.wb().put(com.kwad.components.core.webview.a.a.r.class, new hb());
        el.wb().put(a.b.class, new cl());
        el.wb().put(b.C0454b.class, new gv());
        el.wb().put(com.kwad.components.core.webview.a.a.u.class, new ii());
        el.wb().put(w.b.class, new ej());
        el.wb().put(com.kwad.components.core.webview.a.a.s.class, new hc());
        el.wb().put(com.kwad.sdk.kwai.kwai.kwai.a.class, new eb());
        el.wb().put(com.kwad.components.core.webview.a.a.k.class, new fa());
        el.wb().put(u.a.class, new bz());
        el.wb().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new v());
        el.wb().put(z.a.class, new fq());
        el.wb().put(SplashPreloadManager.PreLoadPara.class, new ge());
        el.wb().put(com.kwad.components.core.webview.a.a.l.class, new fk());
        el.wb().put(n.a.class, new fz());
        el.wb().put(o.a.class, new ga());
        el.wb().put(SplashMonitorInfo.class, new hm());
        el.wb().put(a.C0420a.class, new ci());
        el.wb().put(com.kwad.components.core.webview.a.a.m.class, new fo());
        el.wb().put(com.kwad.components.core.webview.a.a.c.class, new at());
        el.wb().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new x());
        el.wb().put(a.C0413a.class, new dl());
        el.wb().put(a.C0453a.class, new co());
        el.wb().put(w.a.class, new ei());
        el.wb().put(b.a.class, new dm());
        el.wb().put(ak.a.class, new ds());
        el.wb().put(af.a.class, new eq());
    }
}
