package com.kwad.sdk.core.config;

import androidx.media3.exoplayer.DefaultLoadControl;
import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import com.kwad.sdk.core.config.item.r;
import com.kwad.sdk.core.config.item.s;
import com.kwad.sdk.core.imageloader.KSImageLoader;
import java.util.ArrayList;

/* JADX INFO: loaded from: classes4.dex */
public final class c {
    public static final com.kwad.sdk.core.config.item.d ayC = new com.kwad.sdk.core.config.item.d("tkRenderTypeSwitch", false);
    public static final o ayD = new o("feedTKIdleTime", 0L);
    public static k ayE = new k("batchReportCatchLimit", 20);
    public static k ayF = new k("exceptionCollectorSwitch", 1);
    public static k ayG = new k("catchExceptionReportSwitch", 1);
    public static k ayH = new k("mediaPlayerLogReport", 0);
    public static k ayI = new k("didCopySwitch", 1);
    public static k ayJ = new k("enableHodor", 0);
    public static k ayK = new k("speedLimitSwitch", 1);
    public static k ayL = new k("speedLimitThreshold", 200);
    public static k ayM = new k("ksNativeAdCustomSwitch", 0);
    public static k ayN = new k("compoAndSoThreadPoolCoreSize", 0);
    public static k ayO = new k("forceActivateAfterInstalled", 0);
    public static k ayP = new k("spliceVideoInteractionType", 0);
    public static k ayQ = new k("feedLoadOptimizeType", 0);
    public static k ayR = new k("feedLoadOptimizeExternalEnable", 0);
    public static k ayS = new k("nativeAdSlideClickDisable", 0);
    public static r ayT = new r("uaid", "");
    public static o ayU = new o("uaidExpireSec", 0L);
    public static o ayV = new o("uaidRequestDelayTime", 5L);
    public static k ayW = new k("interstitialAdLoadProcessChange", 0);
    public static k ayX = new k("interstitialAdActivityOpt", 0);
    public static k ayY = new k("formAdExitInterceptSwitch", 0);
    public static k ayZ = new k("adLeaveConfirmSwitch", 0);
    public static k aza = new k("viewLandingPageTaskDuration", 15);
    public static k azb = new k("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d azc = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static o azd = new o("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d aze = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d azf = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static com.kwad.sdk.core.config.item.d azg = new com.kwad.sdk.core.config.item.d("commercialLoggerDeviceSwitch", false);
    public static k azh = new k("commercialLoggerSwitch", 1);
    public static r azi = new r("tkSoUrlV7a", "");
    public static r azj = new r("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d azk = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static m azl = new m("playerConfig", null);
    public static s azm = new s("pkgNameList", new ArrayList(0));
    public static s azn = new s("hostList", new ArrayList(0));
    public static s azo = new s("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem azp = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c azq = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem azr = new InstallActivateReminderConfigItem();
    public static com.kwad.sdk.core.config.item.e azs = new com.kwad.sdk.core.config.item.e();
    public static l<Integer> azt = new l<>("adTKGrayConfig");
    public static p azu = new p("realtimeReportActions", "");
    public static q azv = new q();
    public static k azw = new k("appInstallNoticeSecond", 0);
    public static k azx = new k("installFloatingLayerPostion", 0);
    public static k azy = new k("remindInstallStyle", 0);
    public static k azz = new k("remindInstallTime", 60);
    public static k azA = new k("watermarkKwaiIdSwitch", 0);
    public static k azB = new k("insertScreenV2Switch", 0);
    public static k azC = new k("insertScreenAutoPlaySwitch", 0);
    public static j azD = new j("insertScreenV2ShowConfig");
    public static k azE = new k("environmentDetectEnable", 0);
    public static k azF = new k("simCardInfoEnable", 0);
    public static k azG = new k("baseStationEnable", 0);
    public static k azH = new k("sensorEventEnable2", 0);
    public static k azI = new k("lpAutoDownloadApkSwitch", 1);
    public static k azJ = new k("autoDownloadUrlSwitch", 0);
    public static k azK = new k("insertScreenAdType", 0);
    public static k azL = new k("interstitialAutoCallAppCountDaily", 1);
    public static k azM = new k("mediaControlPlaySwitch", 1);
    public static r azN = new r("appStatusSoUrlV7a", "");
    public static r azO = new r("appStatusSoUrlV8a", "");
    public static r azP = new r("appStatusSoVersion", "");
    public static k azQ = new k("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d azR = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static h azS = new h();
    public static com.kwad.sdk.core.config.item.d azT = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d azU = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static r azV = new r("TKSwitchExtra", "");
    public static com.kwad.sdk.core.config.item.d azW = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d azX = new com.kwad.sdk.core.config.item.d("TKJsonSubThread", true);
    public static com.kwad.sdk.core.config.item.d azY = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d azZ = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static k aAa = new k("forceActivate", 0);
    public static k aAb = new k("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d aAc = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static r aAd = new r("nativeAndAnrDynamic", "");
    public static k aAe = new k("kwaiAppVersionSwitch", 1);
    public static com.kwad.sdk.core.config.item.d aAf = new com.kwad.sdk.core.config.item.d("disableLogcatOAID", false);
    public static r aAg = new r("userAgent");
    public static k aAh = new k("biddingLogSwitch", 0);
    public static k aAi = new k("forceActiveThreshold", 5);
    public static k aAj = new k("forceActiveInterval", 3);
    public static k aAk = new k("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d aAl = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static g aAm = new g("adExposureAreaPercent", 0.3f);
    public static g aAn = new g("adExposureTime", -1.0f);
    public static g aAo = new g("drawAdExposureAreaPercent", 0.7f);
    public static g aAp = new g("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d aAq = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d aAr = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static k aAs = new k("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d aAt = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static com.kwad.sdk.core.config.item.d aAu = new com.kwad.sdk.core.config.item.d("forceGetAudioFocus", false);
    public static k aAv = new k("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d aAw = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d aAx = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static o aAy = new o("obiwanLogFilesDiskQuota", 52428800L);
    public static m aAz = new m("logCommandResult", "", false);
    public static o aAA = new o("validClickConvertTime", 1000L);
    public static com.kwad.sdk.core.config.item.d aAB = new com.kwad.sdk.core.config.item.d("eplCommandSwitch", false);
    public static k aAC = new k("playableAutoPlayEnable", 1);
    public static k aAD = new k("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d aAE = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d aAF = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static k aAG = new k("weaponSwitch", 1);
    public static k aAH = new k("kvModeV2", 0);
    public static i aAI = new i();
    public static k aAJ = new k("idcRollbackInterval", 0);
    public static o aAK = new o("currentServerTimeMs");
    public static k aAL = new k("clientProofreadTimeErrorRangeHours", 100);
    public static g aAM = new g("adTraceReportRate", 1.0f);
    public static k aAN = new k("adTraceRepeatEnable", 0);
    public static k aAO = new k("appHeartBeatInterval", 0);
    public static k aAP = new k("insertShowPercent", 100);
    public static k aAQ = new k("adCacheCode", 0);
    public static r aAR = new r("installTipsContentDesc", "");
    public static r aAS = new r("installTipsPositiveActionDesc", "");
    public static r aAT = new r("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d aAU = new com.kwad.sdk.core.config.item.d("threadOptEnable", false);
    public static com.kwad.sdk.core.config.item.d aAV = new com.kwad.sdk.core.config.item.d("resourceWarmupSwitch", false);
    public static k aAW = new k("resourceWarmupDelayTime", 5);
    public static r aAX = new r("perfMonitorV2", "");
    public static k aAY = new k("neoVideoAdaptStrategy", 1);
    public static k aAZ = new k("feedTKLoadTimeOut", Integer.valueOf(DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_MS));
    public static k aBa = new k("drawTKLoadTimeOut", 2000);
    public static com.kwad.sdk.core.config.item.d aBb = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static k aBc = new k("adImageLoaderCacheLimitSize", -1);
    public static com.kwad.sdk.core.config.item.d aBd = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static k aBe = new k("videoCacheOpt", 0);
    public static r aBf = new r("ranger", "");
    public static k aBg = new k("hdrConfig", 0);
    public static r aBh = new r("packageInstall", "");
    public static r aBi = new r("eplV1", "");
    public static r aBj = new r("threadPoolPerfMonitor", "");
    public static r aBk = new r("threadPoolParams", "");
    public static f aBl = new f("crashUploadRate", Double.valueOf(1.0d));
    public static f aBm = new f("adFeedWidthMinPercent", Double.valueOf(0.3d));
    public static com.kwad.sdk.core.config.item.d aBn = new com.kwad.sdk.core.config.item.d("videoPerfMonitor", false);
    public static com.kwad.sdk.core.config.item.d aBo = new com.kwad.sdk.core.config.item.d("enableHookPluginResource", true);
    public static com.kwad.sdk.core.config.item.d aBp = new com.kwad.sdk.core.config.item.d("enableHookWrapperContext", true);
    public static com.kwad.sdk.core.config.item.d aBq = new com.kwad.sdk.core.config.item.d("batchReportSkipJSONParseEnable", false);
    public static com.kwad.sdk.core.config.item.d aBr = new com.kwad.sdk.core.config.item.d("enableAdTrackLog", true);
    public static com.kwad.sdk.core.config.item.d aBs = new com.kwad.sdk.core.config.item.d("usePolicy64LevelDisable", false);
    public static com.kwad.sdk.core.config.item.d aBt = new com.kwad.sdk.core.config.item.d("tkReportInfoSwitch", false);
    public static k aBu = new k("tubeRenderType", 0);
    public static k aBv = new k("useTKAdBrowse", 0);
    public static com.kwad.sdk.core.config.item.d aBw = new com.kwad.sdk.core.config.item.d("enableMediaGetAdInfo", false);
    public static com.kwad.sdk.core.config.item.d aBx = new com.kwad.sdk.core.config.item.d("ecExtInfoSwitch", false);
    public static r aBy = new r("trackBlackUrlConfig", "");
    public static k aBz = new k("tkMemCacheSize", 0);
    public static s aBA = new s("preloadMemCacheTemplateIds", new ArrayList(0));
    public static k aBB = new k("kGeoInfoConfig", 1);
    public static k aBC = new k("appMonitorSwitch", 0);
    public static k aBD = new k("videoCacheErrorCallbackSwitch", 0);
    public static k aBE = new k("tkErrorDetailCount", 1);
    public static k aBF = new k("videoLaunchOptimiseSwitch", 0);
    public static k aBG = new k("enableInitStartMode", 1);
    public static r aBH = new r("localLogConfig", "");
    public static r aBI = new r("adLogRetryConfig", "");
    public static n aBJ = new n("dpSchemeFlags");
    public static com.kwad.sdk.core.config.item.d aBK = new com.kwad.sdk.core.config.item.d("feedAdBgTransparentSwitch");
    public static k aBL = new k("adRequestNum", 1);
    public static k aBM = new k("carouselInterval", Integer.valueOf(KSImageLoader.InnerImageLoadingListener.MAX_DURATION));
    public static o aBN = new o("packageInfoLimiter", 0L);
    public static com.kwad.sdk.core.config.item.d aBO = new com.kwad.sdk.core.config.item.d("showOptimizedProgress");
    public static k aBP = new k("optimizeProgressMethod", 0);
    public static k aBQ = new k("splashLoadTimeOptimize", 0);
    public static o aBR = new o("splashVisibleCheckDelayTime", 500L);
    public static com.kwad.sdk.core.config.item.d aBS = new com.kwad.sdk.core.config.item.d("isWaynePlayerValid", false);
    public static com.kwad.sdk.core.config.item.d aBT = new com.kwad.sdk.core.config.item.d("isWaynePlayerAsDefaultPlayer", false);
    public static m aBU = new m("waynePlayerPlayConfig", null);
    public static k aBV = new k("waynePlayerSupportAndroidApi", 24);
    public static com.kwad.sdk.core.config.item.d aBW = new com.kwad.sdk.core.config.item.d("enableThreadOpt2", false);
    public static m aBX = new m("cheatInfoConfig", null);
    public static m aBY = new m("featureCollectConfig", null);
    public static final k aBZ = new k("installerCheckPkgAbSwitch", 0);
    public static final r aCa = new r("installerCheckExtraPkgs", "");
    public static final k aCb = new k("probeBatch", 0);

    public static void init() {
    }
}
