package com.kwad.sdk.core.b.a;

import com.kwad.components.core.video.a.d;
import com.kwad.components.core.webview.a.a;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.a;
import com.kwad.components.core.webview.jshandler.a.a;
import com.kwad.components.core.webview.jshandler.a.e;
import com.kwad.components.core.webview.jshandler.a.f;
import com.kwad.components.core.webview.jshandler.ag;
import com.kwad.components.core.webview.jshandler.ah;
import com.kwad.components.core.webview.jshandler.aj;
import com.kwad.components.core.webview.jshandler.ak;
import com.kwad.components.core.webview.jshandler.an;
import com.kwad.components.core.webview.jshandler.ao;
import com.kwad.components.core.webview.jshandler.ap;
import com.kwad.components.core.webview.jshandler.as;
import com.kwad.components.core.webview.jshandler.at;
import com.kwad.components.core.webview.jshandler.au;
import com.kwad.components.core.webview.jshandler.av;
import com.kwad.components.core.webview.jshandler.ay;
import com.kwad.components.core.webview.jshandler.ba;
import com.kwad.components.core.webview.jshandler.be;
import com.kwad.components.core.webview.jshandler.bf;
import com.kwad.components.core.webview.jshandler.bg;
import com.kwad.components.core.webview.jshandler.bi;
import com.kwad.components.core.webview.jshandler.e;
import com.kwad.components.core.webview.jshandler.f;
import com.kwad.components.core.webview.jshandler.g;
import com.kwad.components.core.webview.jshandler.h;
import com.kwad.components.core.webview.jshandler.i;
import com.kwad.components.core.webview.jshandler.j;
import com.kwad.components.core.webview.jshandler.l;
import com.kwad.components.core.webview.jshandler.m;
import com.kwad.components.core.webview.jshandler.q;
import com.kwad.components.core.webview.jshandler.u;
import com.kwad.components.core.webview.jshandler.v;
import com.kwad.components.core.webview.jshandler.y;
import com.kwad.components.core.webview.tachikoma.b.h;
import com.kwad.components.core.webview.tachikoma.b.u;
import com.kwad.components.core.webview.tachikoma.b.x;
import com.kwad.sdk.j.a;
import com.kwad.sdk.kgeo.KGeoInfo;
import com.kwad.sdk.mobileid.UaidInfo;
import com.kwad.sdk.resourceCache.model.WarmUpReportMessage;

/* JADX INFO: loaded from: classes4.dex */
public final class db {
    public static void Hk() {
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.z.class, new mc());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.w.class, new lr());
        go.Hl().put(m.a.class, new fx());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.i.class, new el());
        go.Hl().put(bg.a.class, new fm());
        go.Hl().put(com.kwad.sdk.a.a.a.a.class, new fz());
        go.Hl().put(com.kwad.components.core.page.b.a.class, new gt());
        go.Hl().put(a.C0419a.class, new jn());
        go.Hl().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new gq());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.d.class, new br());
        go.Hl().put(ak.a.class, new fo());
        go.Hl().put(com.kwad.components.core.o.c.b.class, new hz());
        go.Hl().put(l.a.class, new ff());
        go.Hl().put(bi.a.class, new gn());
        go.Hl().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new ab());
        go.Hl().put(bf.a.class, new ld());
        go.Hl().put(ag.a.class, new ir());
        go.Hl().put(an.a.class, new de());
        go.Hl().put(m.b.class, new fy());
        go.Hl().put(d.b.class, new lx());
        go.Hl().put(i.a.class, new fc());
        go.Hl().put(j.a.class, new fd());
        go.Hl().put(f.a.class, new ck());
        go.Hl().put(ah.a.class, new is());
        go.Hl().put(as.a.class, new ii());
        go.Hl().put(ba.a.class, new gw());
        go.Hl().put(d.a.class, new lw());
        go.Hl().put(au.b.class, new bk());
        go.Hl().put(com.kwad.components.core.l.a.class, new u());
        go.Hl().put(ao.b.class, new fi());
        go.Hl().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new ad());
        go.Hl().put(WebCardVideoPositionHandler.VideoPosition.class, new mb());
        go.Hl().put(x.a.class, new bn());
        go.Hl().put(u.b.class, new kk());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.f.class, new cl());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.k.class, new gl());
        go.Hl().put(a.C0354a.class, new al());
        go.Hl().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new ac());
        go.Hl().put(f.a.class, new ez());
        go.Hl().put(ap.a.class, new gj());
        go.Hl().put(com.kwad.components.core.video.a.e.class, new mf());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.p.class, new ig());
        go.Hl().put(h.a.class, new fb());
        go.Hl().put(at.a.class, new bg());
        go.Hl().put(KGeoInfo.class, new gp());
        go.Hl().put(ay.a.class, new mg());
        go.Hl().put(h.b.class, new iq());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.c.class, new bp());
        go.Hl().put(com.kwad.components.core.o.c.d.class, new lq());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.t.class, new jv());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.r.class, new js());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.j.class, new fg());
        go.Hl().put(com.kwad.components.core.webview.a.b.class, new ia());
        go.Hl().put(y.a.class, new w());
        go.Hl().put(u.a.class, new ku());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.s.class, new ju());
        go.Hl().put(g.a.class, new fa());
        go.Hl().put(ap.b.class, new gk());
        go.Hl().put(au.a.class, new bj());
        go.Hl().put(a.b.class, new jo());
        go.Hl().put(a.c.class, new hs());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.g.class, new co());
        go.Hl().put(com.kwad.components.core.webview.a.c.class, new ic());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.n.class, new hj());
        go.Hl().put(e.a.class, new jp());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.y.class, new ly());
        go.Hl().put(av.a.class, new bs());
        go.Hl().put(UaidInfo.class, new ln());
        go.Hl().put(be.a.class, new md());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.m.class, new gu());
        go.Hl().put(v.b.class, new kq());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.a.class, new o());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.e.class, new cd());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.b.class, new bl());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.u.class, new jw());
        go.Hl().put(j.b.class, new fe());
        go.Hl().put(q.a.class, new hh());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.v.class, new kj());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.h.class, new dj());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.q.class, new io());
        go.Hl().put(aj.a.class, new ls());
        go.Hl().put(a.C0353a.class, new dq());
        go.Hl().put(WarmUpReportMessage.class, new me());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.x.class, new lu());
        go.Hl().put(e.b.class, new fr());
        go.Hl().put(a.b.class, new dt());
        go.Hl().put(com.kwad.components.core.webview.tachikoma.c.o.class, new ib());
        go.Hl().put(a.C0355a.class, new cf());
    }
}
