package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.ForInvoker;
import com.kwad.sdk.commercial.j.a;
import com.kwad.sdk.commercial.model.HybridLoadMsg;
import com.kwad.sdk.commercial.model.SDKInitMsg;
import com.kwad.sdk.commercial.model.WebCloseStatus;
import com.kwad.sdk.commercial.model.WebViewCommercialMsg;
import com.kwad.sdk.commercial.model.WebViewLoadMsg;
import com.kwad.sdk.core.h.a;
import com.kwad.sdk.core.imageloader.ImageLoaderInfo;
import com.kwad.sdk.core.request.model.StatusInfo;
import com.kwad.sdk.core.response.model.ABParams;
import com.kwad.sdk.core.response.model.AdGlobalConfigInfo;
import com.kwad.sdk.core.response.model.AdInfo;
import com.kwad.sdk.core.response.model.AdMatrixInfo;
import com.kwad.sdk.core.response.model.AdProductInfo;
import com.kwad.sdk.core.response.model.AdStatusInfo;
import com.kwad.sdk.core.response.model.AdStyleInfo;
import com.kwad.sdk.core.response.model.AdTemplate;
import com.kwad.sdk.core.response.model.AdVideoPreCacheConfig;
import com.kwad.sdk.core.response.model.CouponInfo;
import com.kwad.sdk.core.response.model.FeedSlideConf;
import com.kwad.sdk.core.response.model.HttpDnsInfo;
import com.kwad.sdk.core.response.model.PageInfo;
import com.kwad.sdk.core.response.model.PhotoInfo;
import com.kwad.sdk.core.response.model.TKAdLiveShopItemInfo;
import com.kwad.sdk.core.response.model.TemplateConfig;
import com.kwad.sdk.core.response.model.VideoPlayerStatus;
import com.kwad.sdk.core.scene.URLPackage;
import com.kwad.sdk.internal.api.AdLabelImpl;
import com.kwad.sdk.internal.api.NativeAdExtraDataImpl;
import com.kwad.sdk.internal.api.SceneImpl;
import com.kwad.sdk.internal.api.SplashExtraDataImpl;
import com.kwad.sdk.o.l;
import java.util.HashMap;
import java.util.Map;

/* JADX INFO: loaded from: classes4.dex */
public final class go {
    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> aDS;

    static {
        HashMap map = new HashMap();
        aDS = map;
        map.put(AdMatrixInfo.BottomBannerInfo.class, new cc());
        aDS.put(AdMatrixInfo.RotateInfo.class, new jl());
        aDS.put(l.a.C0425a.class, new kp());
        aDS.put(AdStyleInfo.PlayDetailInfo.PatchAdInfo.class, new ik());
        aDS.put(AdInfo.AdBaseInfo.class, new j());
        aDS.put(AdInfo.AdvertiserInfo.class, new bb());
        aDS.put(URLPackage.class, new lm());
        aDS.put(AdMatrixInfo.ShakeInfo.class, new jr());
        aDS.put(com.kwad.sdk.commercial.g.b.class, new fk());
        aDS.put(FeedSlideConf.class, new en());
        aDS.put(AdMatrixInfo.Styles.class, new kx());
        aDS.put(a.C0404a.class, new la());
        aDS.put(AdInfo.AdAggregateInfo.class, new h());
        aDS.put(AdMatrixInfo.ActivityMiddlePageInfo.class, new g());
        aDS.put(AdInfo.AdMaterialInfo.MaterialFeature.class, new hb());
        aDS.put(AdMatrixInfo.MerchantLiveReservationInfo.class, new hg());
        aDS.put(com.kwad.sdk.utils.b.a.class, new gs());
        aDS.put(AdMatrixInfo.RewardVideoTaskInfo.class, new jh());
        aDS.put(NativeAdExtraDataImpl.class, new hk());
        aDS.put(com.kwad.sdk.core.network.j.class, new hy());
        aDS.put(AdInfo.PlayableStyleInfo.class, new it());
        aDS.put(com.kwad.sdk.commercial.e.b.class, new p());
        aDS.put(AdGlobalConfigInfo.CycleAggregationInfo.class, new di());
        aDS.put(AdInfo.CutRuleInfo.class, new dg());
        aDS.put(com.kwad.sdk.h.a.b.class, new ie());
        aDS.put(AdInfo.SmallAppJumpInfo.class, new jy());
        aDS.put(AdMatrixInfo.EndCardInfo.class, new dz());
        aDS.put(AdInfo.CallBackStrategyInfo.class, new ce());
        aDS.put(AdInfo.class, new x());
        aDS.put(AdStyleInfo.PlayEndInfo.AdWebCardInfo.class, new ba());
        aDS.put(AdInfo.NativeAdShakeInfo.class, new hn());
        aDS.put(AdInfo.AdInsertScreenInfo.class, new y());
        aDS.put(WebViewLoadMsg.class, new mj());
        aDS.put(AdInfo.AdTrackInfo.class, new aw());
        aDS.put(AdMatrixInfo.MatrixTag.class, new he());
        aDS.put(AdMatrixInfo.DynamicAdStyleInfo.class, new dy());
        aDS.put(com.kwad.sdk.commercial.f.b.class, new dl());
        aDS.put(StatusInfo.class, new kt());
        aDS.put(AdMatrixInfo.AdInteractionInfo.class, new z());
        aDS.put(AdLabelImpl.class, new aa());
        aDS.put(com.kwad.sdk.commercial.j.b.class, new ay());
        aDS.put(AdMatrixInfo.NativeMatrixAdInfo.class, new hq());
        aDS.put(AdStyleInfo.class, new at());
        aDS.put(AdTemplate.class, new av());
        aDS.put(WebViewCommercialMsg.class, new mi());
        aDS.put(PhotoInfo.BaseInfo.class, new bw());
        aDS.put(AdMatrixInfo.StyleComponentInfo.class, new kv());
        aDS.put(SplashExtraDataImpl.class, new ke());
        aDS.put(AdGlobalConfigInfo.class, new v());
        aDS.put(AdMatrixInfo.class, new ak());
        aDS.put(ABParams.class, new a());
        aDS.put(com.kwad.sdk.core.threads.b.class, new lh());
        aDS.put(StatusInfo.NativeAdStyleControl.class, new ho());
        aDS.put(AdMatrixInfo.SplashSlideInfo.class, new km());
        aDS.put(AdGlobalConfigInfo.NeoScanAggregationSceneInfo.class, new ht());
        aDS.put(AdInfo.AdLiveTypeInfo.class, new ae());
        aDS.put(StatusInfo.NativeAdRequestInfo.class, new hm());
        aDS.put(AdMatrixInfo.NeoVideoInfo.class, new hv());
        aDS.put(CouponInfo.class, new dd());
        aDS.put(com.kwad.sdk.commercial.smallApp.b.class, new jz());
        aDS.put(AdMatrixInfo.TemplateData.class, new lg());
        aDS.put(AdStatusInfo.class, new ar());
        aDS.put(AdMatrixInfo.AdDataV2.class, new r());
        aDS.put(AdInfo.NativeAdInfo.class, new hl());
        aDS.put(AdStyleInfo.PlayDetailInfo.DetailTopToolBarInfo.class, new dn());
        aDS.put(AdStyleInfo.PlayEndInfo.class, new ip());
        aDS.put(com.kwad.sdk.commercial.e.c.class, new q());
        aDS.put(AdMatrixInfo.FullScreenInfo.class, new ew());
        aDS.put(AdMatrixInfo.SplashActionBarInfo.class, new kb());
        aDS.put(AdStyleInfo.PlayDetailInfo.DetailWebCardInfo.class, new Cdo());
        aDS.put(AdInfo.H5Config.class, new fh());
        aDS.put(AdMatrixInfo.StyleInfo.class, new kw());
        aDS.put(AdMatrixInfo.ActionBarInfoNew.class, new d());
        aDS.put(AdVideoPreCacheConfig.class, new az());
        aDS.put(VideoPlayerStatus.class, new ma());
        aDS.put(com.kwad.sdk.core.network.i.class, new hx());
        aDS.put(AdMatrixInfo.SplashInfo.class, new kf());
        aDS.put(AdInfo.AdConversionInfo.class, new m());
        aDS.put(AdMatrixInfo.SplashPlayCardTKInfo.class, new ki());
        aDS.put(AdMatrixInfo.FeedInfo.class, new ek());
        aDS.put(AdInfo.UnDownloadRegionConf.class, new lp());
        aDS.put(AdMatrixInfo.InterstitialCardInfo.class, new ge());
        aDS.put(AdStyleInfo.PlayDetailInfo.DrawAdInfo.class, new dv());
        aDS.put(AdInfo.AdPreloadInfo.class, new am());
        aDS.put(a.C0390a.class, new ll());
        aDS.put(AdInfo.AdShowVideoH5Info.class, new ap());
        aDS.put(AdMatrixInfo.PreLandingPageTKInfo.class, new iv());
        aDS.put(AdInfo.AdDrawInfo.class, new s());
        aDS.put(PhotoInfo.class, new im());
        aDS.put(com.kwad.sdk.commercial.b.b.class, new bm());
        aDS.put(AdInfo.AdConversionInfo.DeeplinkItemInfo.class, new dk());
        aDS.put(l.a.class, new ml());
        aDS.put(AdMatrixInfo.RewardWebTaskCloseInfo.class, new ji());
        aDS.put(AdMatrixInfo.RotateDegreeInfo.class, new jk());
        aDS.put(com.kwad.sdk.core.report.j.class, new eb());
        aDS.put(AdMatrixInfo.CycleAggregateInfo.class, new dh());
        aDS.put(SDKInitMsg.class, new jm());
        aDS.put(AdInfo.MaterialSize.class, new hd());
        aDS.put(AdMatrixInfo.MatrixTemplate.class, new hf());
        aDS.put(com.kwad.sdk.core.config.d.class, new Cif());
        aDS.put(AdMatrixInfo.MerchantLiveReservationInfo.LiveReservationPlayEndInfo.class, new gv());
        aDS.put(com.kwad.sdk.commercial.c.a.class, new bx());
        aDS.put(AdMatrixInfo.SlideInfo.class, new jx());
        aDS.put(AdInfo.AdBannerInfo.class, new i());
        aDS.put(AdMatrixInfo.SplashEndCardTKInfo.class, new kd());
        aDS.put(AdInfo.AdRewardInfo.class, new ao());
        aDS.put(com.kwad.sdk.commercial.i.a.class, new gz());
        aDS.put(AdMatrixInfo.RewardVideoInteractInfo.class, new jg());
        aDS.put(AdStyleInfo.FeedAdInfo.class, new ei());
        aDS.put(AdInfo.AdFeedInfo.class, new t());
        aDS.put(com.kwad.sdk.core.request.model.b.class, new dp());
        aDS.put(com.kwad.sdk.core.request.model.d.class, new hw());
        aDS.put(AdStyleInfo.ExposeTagInfo.class, new ee());
        aDS.put(AdStyleInfo.PlayDetailInfo.WidgetAdInfo.class, new mk());
        aDS.put(com.kwad.sdk.commercial.d.b.class, new n());
        aDS.put(HybridLoadMsg.class, new fq());
        aDS.put(AdStyleInfo.AdBrowseInfo.class, new l());
        aDS.put(AdStyleInfo.PlayEndInfo.EndTopToolBarInfo.class, new ea());
        aDS.put(AdMatrixInfo.ComponentTemplateInfo.class, new cr());
        aDS.put(AdStyleInfo.PlayDetailInfo.ActionBarInfo.class, new c());
        aDS.put(AdInfo.AdSplashInfo.class, new aq());
        aDS.put(AdMatrixInfo.DownloadTexts.class, new du());
        aDS.put(SceneImpl.class, new jq());
        aDS.put(com.kwad.sdk.h.a.a.class, new id());
        aDS.put(AdMatrixInfo.BaseMatrixTemplate.class, new by());
        aDS.put(AdInfo.UnDownloadConf.class, new lo());
        aDS.put(AdStyleInfo.PlayDetailInfo.PatchEcInfo.class, new il());
        aDS.put(AdInfo.ComplianceInfo.class, new cp());
        aDS.put(AdProductInfo.class, new an());
        aDS.put(AdInfo.RewardFraudVerifyInfo.class, new jc());
        aDS.put(com.kwad.sdk.commercial.a.b.class, new bi());
        aDS.put(WebCloseStatus.class, new mh());
        aDS.put(HttpDnsInfo.class, new fp());
        aDS.put(com.kwad.sdk.core.request.model.g.class, new lt());
        aDS.put(com.kwad.sdk.core.threads.d.class, new li());
        aDS.put(AdStyleInfo.PlayDetailInfo.DetailCommonInfo.class, new dm());
        aDS.put(ImageLoaderInfo.class, new ft());
        aDS.put(StatusInfo.SplashStyleControl.class, new kn());
        aDS.put(AdStyleInfo.ExtraDisplayInfo.class, new eg());
        aDS.put(PhotoInfo.VideoInfo.class, new lv());
        aDS.put(AdInfo.DownloadSafeInfo.class, new ds());
        aDS.put(AdInfo.FullScreenVideoInfo.class, new ex());
        aDS.put(com.kwad.sdk.core.request.model.f.class, new lc());
        aDS.put(AdMatrixInfo.InstalledActivateInfo.class, new ga());
        aDS.put(HttpDnsInfo.IpInfo.class, new gi());
        aDS.put(TKAdLiveShopItemInfo.class, new ky());
        aDS.put(AdInfo.AdStyleConfInfo.class, new as());
        aDS.put(AdProductInfo.SpikeInfo.class, new ka());
        aDS.put(PageInfo.class, new ih());
        aDS.put(TemplateConfig.class, new le());
        aDS.put(AdMatrixInfo.ComponentParam.class, new cq());
        aDS.put(AdMatrixInfo.AggregationCardInfo.class, new bc());
        aDS.put(StatusInfo.SplashAdInfo.class, new kc());
        aDS.put(AdInfo.AdMaterialInfo.class, new aj());
        aDS.put(AdStyleInfo.PlayDetailInfo.class, new in());
        Hk();
    }

    @ForInvoker(methodId = "registerHolder")
    private static void Hk() {
        cs.Hk();
        ct.Hk();
        cu.Hk();
        cv.Hk();
        cw.Hk();
        cx.Hk();
        cy.Hk();
        cz.Hk();
        da.Hk();
        db.Hk();
        ep.Hk();
        eq.Hk();
        er.Hk();
        es.Hk();
        et.Hk();
        eu.Hk();
    }

    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> Hl() {
        return aDS;
    }

    public static com.kwad.sdk.core.d getHolder(Class<? extends com.kwad.sdk.core.response.a.a> cls) {
        return aDS.get(cls);
    }
}
