package com.kwad.sdk.core.config;

import com.bytedance.sdk.openadsdk.downloadnew.core.TTDownloadField;
import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.e;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import com.tencent.smtt.sdk.TbsMediaPlayer;
import java.util.ArrayList;

/* JADX INFO: loaded from: classes3.dex */
public final class c {
    public static k abq = new k("batchReportCatchLimit", 20);
    public static k abr = new k("exceptionCollectorSwitch", 1);
    public static k abs = new k("mediaPlayerLogReport", 0);
    public static k abt = new k("didCopySwitch", 1);
    public static k abu = new k("enableHodor", 0);
    public static k abv = new k("speedLimitSwitch", 1);
    public static k abw = new k("speedLimitThreshold", 200);
    public static k abx = new k("ksNativeAdCustomSwitch", 0);
    public static k aby = new k("forceActivateAfterInstalled", 0);
    public static k abz = new k("spliceVideoInteractionType", 0);
    public static k abA = new k("formAdExitInterceptSwitch", 0);
    public static k abB = new k("adLeaveConfirmSwitch", 0);
    public static k abC = new k("viewLandingPageTaskDuration", 15);
    public static k abD = new k("rewardAdVideoPreCacheSize", Integer.valueOf(TbsMediaPlayer.TbsMediaPlayerListener.MEDIA_INFO_BAD_INTERLEAVING));
    public static com.kwad.sdk.core.config.item.d abE = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static m abF = new m("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d abG = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d abH = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static k abI = new k("commercialLoggerSwitch", 1);
    public static p abJ = new p("tkSoUrlV7a", "");
    public static p abK = new p("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d abL = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static l abM = new l("playerConfig", null);
    public static q abN = new q("pkgNameList", new ArrayList(0));
    public static q abO = new q("hostList", new ArrayList(0));
    public static q abP = new q("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem abQ = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c abR = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem abS = new InstallActivateReminderConfigItem();
    public static e abT = new e();
    public static n abU = new n("realtimeReportActions", "");
    public static o abV = new o();
    public static k abW = new k("appInstallNoticeSecond", 0);
    public static k abX = new k("installFloatingLayerPostion", 0);
    public static k abY = new k("remindInstallStyle", 0);
    public static k abZ = new k("remindInstallTime", 60);
    public static k aca = new k("watermarkKwaiIdSwitch", 0);
    public static k acb = new k("insertScreenV2Switch", 0);
    public static k acc = new k("insertScreenAutoPlaySwitch", 0);
    public static j acd = new j("insertScreenV2ShowConfig");
    public static k ace = new k("environmentDetectEnable", 0);
    public static k acf = new k("simCardInfoEnable", 0);
    public static k acg = new k("baseStationEnable", 0);
    public static k ach = new k("sensorEventEnable2", 0);
    public static k aci = new k("lpAutoDownloadApkSwitch", 1);
    public static k acj = new k("autoDownloadUrlSwitch", 0);
    public static k ack = new k("insertScreenAdType", 0);
    public static k acl = new k("interstitialAutoCallAppCountDaily", 1);
    public static k acm = new k("mediaControlPlaySwitch", 1);
    public static p acn = new p("appStatusSoUrlV7a", "");
    public static p aco = new p("appStatusSoUrlV8a", "");
    public static p acp = new p("appStatusSoVersion", "");
    public static k acq = new k("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d acr = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static h acs = new h();
    public static com.kwad.sdk.core.config.item.d act = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d acu = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static com.kwad.sdk.core.config.item.d acv = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d acw = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d acx = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static k acy = new k("forceActivate", 0);
    public static k acz = new k("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d acA = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static k acB = new k("enableAnrReportReal", 0);
    public static k acC = new k("enableNativeCrashReport", 0);
    public static p acD = new p("exceptionSoUrlV7a", "");
    public static p acE = new p("exceptionSoUrlV8a", "");
    public static k acF = new k("kwaiAppVersionSwitch", 1);
    public static p acG = new p(TTDownloadField.TT_USERAGENT, com.kwad.sdk.core.network.q.getDefaultUserAgent());
    public static k acH = new k("biddingLogSwitch", 0);
    public static k acI = new k("forceActiveThreshold", 5);
    public static k acJ = new k("forceActiveInterval", 3);
    public static k acK = new k("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d acL = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static g acM = new g("adExposureAreaPercent", 0.3f);
    public static g acN = new g("adExposureTime", -1.0f);
    public static g acO = new g("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d acP = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d acQ = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static k acR = new k("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d acS = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static k acT = new k("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d acU = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d acV = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static m acW = new m("obiwanLogFilesDiskQuota", 52428800L);
    public static l acX = new l("logCommandResult", "", false);
    public static m acY = new m("validClickConvertTime", 1000L);
    public static k acZ = new k("playableAutoPlayEnable", 1);
    public static k ada = new k("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d adb = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d adc = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static k add = new k("weaponSwitch", 1);
    public static k ade = new k("kvModeV2", 0);
    public static i adf = new i();
    public static m adg = new m("currentServerTimeMs");
    public static k adh = new k("clientProofreadTimeErrorRangeHours", 100);
    public static g adi = new g("adTraceReportRate", 1.0f);
    public static k adj = new k("adTraceRepeatEnable", 0);
    public static k adk = new k("appHeartBeatInterval", 0);
    public static k adl = new k("adCacheCode", 0);
    public static p adm = new p("installTipsContentDesc", "");
    public static p adn = new p("installTipsPositiveActionDesc", "");
    public static p ado = new p("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d adp = new com.kwad.sdk.core.config.item.d("threadOptEnable", true);
    public static p adq = new p("perfMonitorV2", "");
    public static k adr = new k("neoVideoAdaptStrategy", 1);
    public static com.kwad.sdk.core.config.item.d ads = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static com.kwad.sdk.core.config.item.d adt = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static p adu = new p("ranger", "");
    public static p adv = new p("threadPoolPerfMonitor", "");
    public static f adw = new f("crashUploadRate", Double.valueOf(1.0d));

    public static void init() {
    }
}
